# Generated by Django 3.2.8 on 2023-03-01 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Shop', 'Shop'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Land', 'Land')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='Images')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('WhatsApp_no', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('Owner', 'Owner'), ('Agent', 'Agent')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'realtors',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Security', models.BooleanField(default=False)),
                ('Parking', models.BooleanField(default=False)),
                ('Internet', models.BooleanField(default=False)),
                ('Playground', models.BooleanField(default=False)),
                ('Furnished', models.BooleanField(default=False)),
                ('Near_Shopping_Mall', models.BooleanField(default=False)),
                ('Balcony', models.BooleanField(default=False)),
                ('Backup_water_supply', models.BooleanField(default=False)),
                ('Backup_electricity_supply', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('no_of_bedroom', models.IntegerField(null=True)),
                ('no_of_bathroom', models.IntegerField(null=True)),
                ('size_of_land', models.CharField(blank=True, max_length=100, null=True)),
                ('size_of_space', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('list', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Morgage', 'Morgage')], max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('main_photo', models.ImageField(upload_to='Images')),
                ('photo_1', models.ImageField(upload_to='Images')),
                ('photo_2', models.ImageField(upload_to='Images')),
                ('photo_3', models.ImageField(upload_to='Images')),
                ('photo_4', models.ImageField(upload_to='Images')),
                ('photo_5', models.ImageField(upload_to='Images')),
                ('availability', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=200, null=True)),
                ('date_of_listing', models.DateTimeField(auto_now_add=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='REALESTATE.realtor')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='REALESTATE.tag')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
