# Generated by Django 3.2.8 on 2023-03-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REALESTATE', '0002_alter_realtor_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='name',
            new_name='First_name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='Last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
