# Generated by Django 3.2.8 on 2023-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REALESTATE', '0003_auto_20230302_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='lee.png', null=True, upload_to='Images'),
        ),
    ]
