# Generated by Django 3.2.8 on 2023-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REALESTATE', '0006_alter_realtor_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-date_of_listing'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='availability',
            field=models.BooleanField(max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-date_of_listing'], name='REALESTATE__date_of_3dca8b_idx'),
        ),
    ]
