# Generated by Django 3.2.8 on 2023-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REALESTATE', '0007_auto_20230826_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='county',
        ),
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ward',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
